#!/bin/bash
echo Hello World
echo command line count: $#
cmd=$1
scriptpath=`realpath $0`
echo command to execute: $cmd
echo ${cmd,} ${cmd,,}

getContainerId()
{
    echo $(sudo docker ps -a | grep "$1" | awk '{print $1}')
}

getImageId()
{
    echo $(sudo docker images | grep "$1" | awk '{print $3}')
}

case ${cmd,,} in
    tfver)
        python -c 'import matplotlib; print("matplotlib version: {}".format(matplotlib.__version__))'
        python -c 'import numpy as np; print("numpy version: {}".format(np.__version__))'
        python -c 'import tensorflow as tf; print("tensorflow version: {}".format(tf.VERSION))'
        ;;
    tfup)
        $scriptpath tfupdate
        ;;
    tfupdate)
	echo pip install -q --upgrade matplotlib
	pip install -q --upgrade matplotlib
	echo pip install -q --upgrade tensorflow
	pip install -q --upgrade tensorflow
	;;
    scratches)
        echo $scriptpath
        echo `realpath $0`
        ;;
    *)
	echo unknown command ${cmd,,}
	;;
esac
