#!/bin/bash
echo Hello World
echo command line count: $#
cmd=$1
scriptpath=`realpath $0`
echo command to execute: $cmd
echo ${cmd,} ${cmd,,}

getContainerId()
{
    echo $(sudo docker ps -a | grep "$1" | awk '{print $1}')
}

getImageId()
{
    echo $(sudo docker images | grep "$1" | awk '{print $3}')
}

case ${cmd,,} in
    tfver)
        $scriptpath tfversion
        ;;
    tfversion)
        python -c 'import sys; print("Python version:\n{}".format(sys.version))'
        python -c 'import matplotlib; print("matplotlib version: {}".format(matplotlib.__version__))'
        python -c 'import numpy as np; print("numpy version: {}".format(np.__version__))'
        python -c 'import tensorflow as tf; print("tensorflow version: {}".format(tf.__version__))'
        python -c 'import requests; print("requests version: {}".format(requests.__version__))'
        python -c 'import html5lib; print("html5lib version: {}".format(html5lib.__version__))'
    echo 'npm version:' $(npm --version)
        ;;
    tfup)
        $scriptpath tfupdate
        ;;
    tfupdate)
        $scriptpath tfver
    echo pip install -q --upgrade matplotlib
    pip install -q --upgrade matplotlib
    echo pip install -q --upgrade grpcio
    pip install -q --upgrade grpcio
    echo pip install -q --upgrade tensorflow
    pip install -q --upgrade tensorflow
    echo pip install -q html5lib
    pip install -q html5lib
    echo npm install -g npm@latest
    echo short version: npm i -g npm
    npm install -g npm@latest
        $scriptpath tfversion
    ;;
    scratches)
        echo $scriptpath
        echo `realpath $0`
        ;;
    *)
    echo unknown command ${cmd,,}
    ;;
esac
