version: '3'

services:
  sci-notebook:
    image: jupyter/tensorflow-notebook:${TAG:-latest}
    ports:
      - "8888:8888"
      - "6006:6006"
      - "8880:1880"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./matplotlib:/home/jovyan/matplotlib
      - ./scripts:/home/jovyan/scripts
      - ./noderedex:/home/jovyan/noderedex