version: '2'

services:
  sci-notebook:
    image: jupyter/tensorflow-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./matplotlib:/home/jovyan/matplotlib
