version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - ./:/data
    ports:
      - "10433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=m(!)sq1INdocker

  dotnet:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    command: sh /workplace/idle.sh
    volumes:
      - ./:/workplace
    ports:
      - 980:80
    depends_on:
      - mssql
