version: '3.1'

services:
  db:
    # image: mysql:5.7
    image: mysql
    volumes:
      # - db_data:/var/lib/mysql
      # - /home/cywang/GIT/docker/wordpress/db_data:/var/lib/mysql
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    # depends_on:
    #   - db
    image: wordpress
    volumes:
      - ./workplace:/workplace
    ports:
      - "980:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      # WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      
# volumes:
#   db_data:
#     external:
#       db_data
