version: '2'

services:
  aosp:
    # image: kylemanna/aosp:latest
    build: .
    command: /bin/bash -c "while true; do foo; sleep 20; done"
    volumes:
      - /tmp/ccache:/ccache
      - ./project:/application