version: '2'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'keycloak'
      POSTGRES_ROOT_PASSWORD: 'test'
    volumes:
      - ./postgres:/mnt/shares/postgres
  keycloak:
    image: jboss/keycloak-postgres
    ports:
      - "800:8080"
    links:
      - postgres
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: 'postgres'
      POSTGRES_DATABASE: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'keycloak'
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      POSTGRES_ROOT_PASSWORD: 'test'
    depends_on:
      - postgres
    volumes:
      - ./keycloak:/mnt/shares/keycloak
  tomcat_keycloak:
    build: .
    ports:
      - "880:8080"
    links:
      - keycloak
    volumes:
      - ./web:/mnt/shares/web
      - ./scratches:/mnt/shares/scratches

