#
#

version: '2'

services:
  mygame:
    build: .
    # image: sjawhar/pygame
    command: sh /code/idle.sh
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/code
    ports:
      - "900:8000"
      - "1500:5000"
