#
# touch Gemfile.lock
# docker-compose run web rails new . --force --database=postgresql --skip-bundle
# sudo chown -R $USER:$USER .
# docker-compose build (if Gemfile is modified)
# docker-compose run web rails db:create

version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'keycloak'
      POSTGRES_ROOT_PASSWORD: 'test'
    ports:
      - "5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db